export const sharedIdeas = [
  {
    id: 'admin-idea-1',
    category: 'Storytelling',
    title: 'A day told through tiny details',
    description: 'Capture small moments and shape them into a warm, cinematic story.',
    tag: 'Short-form video',
    postedBy: 'Admin',
    date: 'Oct 08, 2026',
    status: 'Featured idea',
  },
  {
    id: 'admin-idea-2',
    category: 'Visual concept',
    title: 'One location, three different moods',
    description: 'Revisit the same place at different times with distinct lighting and sound.',
    tag: 'Photography',
    postedBy: 'Admin',
    date: 'Oct 08, 2026',
    status: 'Featured idea',
  },
  {
    id: 'admin-idea-3',
    category: 'Audience engagement',
    title: 'Let followers choose the next chapter',
    description: 'Turn audience comments into the next episode in a continuing series.',
    tag: 'Community',
    postedBy: 'Admin',
    date: 'Oct 08, 2026',
    status: 'Featured idea',
  },
  {
    id: 'admin-idea-4',
    category: 'Educational content',
    title: 'Explain one difficult idea simply',
    description: 'Use a familiar object or everyday example to make a complex topic click.',
    postedBy: 'Admin',
    tag: 'Creator tip',
    date: 'Oct 08, 2026',
    status: 'Featured idea',
  },
  {
    id: 'admin-idea-5',
    category: 'Creative challenge',
    title: 'Make something from what you already have',
    description: 'Create a useful or beautiful result using only materials already nearby.',
    postedBy: 'Admin',
    tag: 'DIY',
    date: 'Oct 08, 2026',
    status: 'Featured idea',
  },
  {
    id: 'admin-idea-6',
    category: 'Behind the scenes',
    title: 'Show the process, not just the result',
    description: 'Share the unexpected steps, small fixes, and decisions behind your final work.',
    tag: 'Process',
    postedBy: 'Admin',
    date: 'Oct 08, 2026',
    status: 'Featured idea',
  },
];
